// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}
