// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenVerificationURL(arg1) {
  return window['go']['main']['App']['OpenVerificationURL'](arg1);
}

export function PollDeviceLogin(arg1) {
  return window['go']['main']['App']['PollDeviceLogin'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartDeviceLogin(arg1, arg2) {
  return window['go']['main']['App']['StartDeviceLogin'](arg1, arg2);
}
