// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {auth} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetAutoStart():Promise<boolean>;

export function GetSettings():Promise<main.SettingsData>;

export function HideWindow():Promise<void>;

export function IsConnected():Promise<boolean>;

export function Logout():Promise<void>;

export function OpenVerificationURL(arg1:string):Promise<void>;

export function PollDeviceLogin(arg1:string):Promise<auth.DeviceTokenResponse>;

export function QuitApp():Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartDeviceLogin(arg1:string,arg2:string):Promise<auth.DeviceCodeResponse>;
